language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install codecov
  - pip install coveralls
  - pip install pycodestyle
script:
  - pycodestyle .
  - coverage run --source=src setup.py test
after_success:
  - coveralls
  - codecov
